import Header from "@/components/Header"
import Head from "next/head"
import Image from "next/image"
import { SearchIcon, MicrophoneIcon } from "@heroicons/react/solid"
import Footer from "@/components/Footer"
import { useRouter } from "next/router"
import { useRef } from "react"

export default function Home() {
    const router = useRouter()
    const searchInputRef = useRef(null)

    function search(e) {
        e.preventDefault()
        const term = searchInputRef.current.value
        if (!term || term === "") return

        router.push(`/search?term=${term.trim()}&searchType=`)
    }

    return (
        <div>
            <Head>
                <title>Google Clone</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="./favicon.io" />
            </Head>

            {/* Header */}
            <Header />

            {/* Body */}
            <form className="flex flex-col items-center mt-40">
                <Image
                    alt="Google Logo"
                    src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Google_2015_logo.svg/220px-Google_2015_logo.svg.png"
                    width={300}
                    height={100}
                    style={{ objectFit: "cover" }}
                />
                <div className="flex w-full mt-5 mx-auto max-w-[90%] border border-gray-200 hover:shadow-lg focus-within:shadow-lg py-3 px-5 rounded-full items-center sm:max-w-xl lg:max-w-2xl">
                    <SearchIcon className="h-5 text-gray-500 mr-3" />
                    <input
                        ref={searchInputRef}
                        className="flex-grow focus:outline-none"
                        type="text"
                        name=""
                        id=""
                    />
                    <MicrophoneIcon className="h-5" />
                </div>
                <div className="flex justify-center flex-col sm:flex-row w-1/2 space-y-2 mt-8 sm:space-y-0 sm:space-x-4">
                    <button onClick={search} className="btn">
                        Google Search
                    </button>
                    <button className="btn">I&apos;m feeling lucky</button>
                </div>
            </form>

            {/* Footer */}
            <Footer />
        </div>
    )
}
